services:
  - type: web
    name: boda-zaida-sheila
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: ADMIN_PASSWORD
        generateValue: true
